/*
 *
 * StaffMain constants
 *
 */

export const DEFAULT_ACTION = 'app/StaffMain/DEFAULT_ACTION';

export const REGISTER_STAFF = 'app/StaffMain/REGISTER_STAFF';
export const REGISTER_STAFF_SUCCESS = 'app/StaffMain/REGISTER_STAFF_SUCCESS';
export const REGISTER_STAFF_FAILURE = 'app/StaffMain/REGISTER_STAFF_FAILURE';
export const SET_UNCLAIMED_CHATS = 'app/StaffMain/SET_UNCLAIMED_CHATS';
export const ADD_UNCLAIMED_CHAT = 'app/StaffMain/ADD_UNCLAIMED_CHAT';
export const REMOVE_UNCLAIMED_CHAT = 'app/StaffMain/REMOVE_UNCLAIMED_CHAT';
export const REMOVE_UNCLAIMED_CHAT_BY_VISITOR_ID =
  'app/StaffMain/REMOVE_UNCLAIMED_CHAT_BY_VISITOR_ID';
export const ADD_ACTIVE_CHAT = 'app/StaffMain/ADD_ACTIVE_CHAT';
export const REMOVE_ACTIVE_CHAT = 'app/StaffMain/REMOVE_ACTIVE_CHAT';
export const REMOVE_ACTIVE_CHAT_BY_ROOM_ID = 'app/StaffMain/REMOVE_ACTIVE_CHAT_BY_ROOM_ID';
export const RESET = 'app/StaffMain/RESET';
export const REFRESH_AUTH_TOKEN = 'app/StaffMain/REFRESH_AUTH_TOKEN';
export const ADD_MESSAGE_FROM_UNCLAIMED_CHAT =
  'app/StaffMain/ADD_MESSAGE_FROM_UNCLAIMED_CHAT';
export const ADD_MESSAGE_FROM_ACTIVE_CHAT =
  'app/StaffMain/ADD_MESSAGE_FROM_ACTIVE_CHAT';
export const ADD_MESSAGE_FROM_ACTIVE_CHAT_BY_VISITOR_ID =
  'app/StaffMain/ADD_MESSAGE_FROM_ACTIVE_CHAT_BY_VISITOR_ID';
export const ADD_MESSAGE_FROM_UNCLAIMED_CHAT_BY_VISITOR_ID =
  'app/StaffMain/ADD_MESSAGE_FROM_UNCLAIMED_CHAT_BY_VISITOR_ID';
export const SET_HAS_MORE_MESSAGES = 'app/StaffMain/SET_HAS_MORE_MESSAGES';
export const ADD_MESSAGE_HISTORY = 'app/StaffMain/ADD_MESSAGE_HISTORY';
export const LOAD_VOLUNTEERS = 'app/StaffMain/LOAD_VOLUNTEERS';
export const LOAD_ALL_VOLUNTEERS = 'app/StaffMain/LOAD_ALL_VOLUNTEERS';
export const LOAD_SUPERVISORS = 'app/StaffMain/LOAD_SUPERVISORS';
export const LOAD_ALL_SUPERVISORS = 'app/StaffMain/LOAD_ALL_SUPERVISORS';
export const SHOW_LOADED_MESSAGE_HISTORY =
  'app/StaffMain/SHOW_LOADED_MESSAGE_HISTORY';
export const LOAD_CHAT_HISTORY = 'app/StaffMain/LOAD_CHAT_HISTORY';
export const LOG_OUT = 'app/StaffMain/LOG_OUT';
export const SUBMIT_SETTINGS = 'app/StaffMain/SUBMIT_SETTINGS';
export const UPDATE_USER = 'app/StaffMain/UPDATE_USER';
export const CLEAR_UNREAD_COUNT = 'app/StaffMain/CLEAR_UNREAD_COUNT';
export const INCREMENT_UNREAD_COUNT = 'app/StaffMain/INCREMENT_UNREAD_COUNT';
export const ADD_ONLINE_USER = 'app/StaffMain/ADD_ONLINE_USER';
export const SET_ONLINE_USERS = 'app/StaffMain/SET_ONLINE_USERS'
export const REMOVE_ONLINE_USER = 'app/StaffMain/REMOVE_ONLINE_USER';
export const ADD_ONLINE_VISITOR = 'app/StaffMain/ADD_ONLINE_VISITOR';
export const SET_ONLINE_VISITORS = 'app/StaffMain/SET_ONLINE_VISITORS'
export const REMOVE_ONLINE_VISITOR = 'app/StaffMain/REMOVE_ONLINE_VISITOR';

export const LOAD_ALL_VISITORS = 'app/StaffMain/LOAD_ALL_VISITORS';
export const LOAD_BOOKMARKED_CHATS = 'app/StaffMain/LOAD_BOOKMARKED_CHATS';
export const ADD_TO_ALL_VISITORS = 'app/StaffMain/ADD_TO_ALL_VISITORS';
export const REMOVE_FROM_ALL_VISITORS = 'app/StaffMain/REMOVE_FROM_ALL_VISITORS';
export const ADD_MESSAGES_BEFORE_FOR_SUPERVISOR_PANEL = 'app/StaffMain/ADD_MESSAGES_BEFORE_FOR_SUPERVISOR_PANEL';
export const LOAD_MESSAGES_BEFORE_FOR_SUPERVISOR_PANEL = 'app/StaffMain/LOAD_MESSAGES_BEFORE_FOR_SUPERVISOR_PANEL';
export const SHOW_MESSAGES_BEFORE_FOR_SUPERVISOR_PANEL = 'app/StaffMain/SHOW_MESSAGES_BEFORE_FOR_SUPERVISOR_PANEL';
export const ADD_MESSAGES_AFTER_FOR_SUPERVISOR_PANEL = 'app/StaffMain/ADD_MESSAGES_AFTER_FOR_SUPERVISOR_PANEL';
export const LOAD_MESSAGES_AFTER_FOR_SUPERVISOR_PANEL = 'app/StaffMain/LOAD_MESSAGES_AFTER_FOR_SUPERVISOR_PANEL';
export const SHOW_MESSAGES_AFTER_FOR_SUPERVISOR_PANEL = 'app/StaffMain/SHOW_MESSAGES_AFTER_FOR_SUPERVISOR_PANEL';
export const SET_MESSAGES_FOR_SUPERVISOR_PANEL = 'app/StaffMain/SET_MESSAGES_FOR_SUPERVISOR_PANEL';
export const REMOVE_VISITOR_FROM_ONGOING_CHATS = 'app/StaffMain/REMOVE_VISITOR_FROM_ONGOING_CHATS';
export const ADD_VISITOR_FROM_ONGOING_CHATS = 'app/StaffMain/ADD_VISITOR_FROM_ONGOING_CHATS';
export const REMOVE_VISITOR_FROM_BOOKMARKED_CHATS = 'app/StaffMain/REMOVE_VISITOR_FROM_BOOKMARKED_CHATS';
export const ADD_VISITORS_TO_BOOKMARKED_CHATS = 'app/StaffMain/ADD_VISITORS_TO_BOOKMARKED_CHATS';
export const REMOVE_VISITOR_FROM_UNREAD_CHATS = 'app/StaffMain/REMOVE_VISITOR_FROM_UNREAD_CHATS';
export const SET_VISITORS_FROM_UNREAD_CHATS = 'app/StaffMain/SET_VISITORS_FROM_UNREAD_CHATS';
export const SET_LAST_SEEN_MESSAGE_ID = 'app/StaffMain/SET_LAST_SEEN_MESSAGE_ID';

export const SET_VISITOR_BOOKMARK = 'app/StaffMain/SET_VISITOR_BOOKMARK';
export const LOAD_LAST_UNREAD = 'app/StaffMain/LOAD_LAST_UNREAD';
export const SET_UNREAD_CHATS = 'app/StaffMain/SET_UNREAD_CHATS';
export const LOAD_UNREAD_CHATS = 'app/StaffMain/LOAD_UNREAD_CHATS';
export const SET_VISITOR_TALKING_TO = 'app/StaffMain/SET_VISITOR_TALKING_TO';
export const ADD_MESSAGE_FOR_SUPERVISOR_PANEL = 'app/StaffMain/ADD_MESSAGE_FOR_SUPERVISOR_PANEL';

export const SET_OFFLINE_UNCLAIMED_CHATS = 'app/StaffMain/SET_OFFLINE_UNCLAIMED_CHATS';
export const ADD_OFFLINE_UNCLAIMED_CHAT = 'app/StaffMain/ADD_OFFLINE_UNCLAIMED_CHAT';
export const REMOVE_OFFLINE_UNCLAIMED_CHAT = 'app/StaffMain/REMOVE_OFFLINE_UNCLAIMED_CHAT';

export const SET_FLAGGED_CHATS = 'app/StaffMain/SET_FLAGGED_CHATS';
export const ADD_FLAGGED_CHAT = 'app/StaffMain/ADD_FLAGGED_CHAT';
export const REMOVE_FLAGGED_CHAT = 'app/StaffMain/REMOVE_FLAGGED_CHAT';

export const CHANGE_CHAT_PRIORITY = 'app/StaffMain/CHANGE_CHAT_PRIORITY';

export const ADD_MESSAGE_FOR_STAFF_PANEL = 'app/StaffMain/ADD_MESSAGE_FOR_STAFF_PANEL';
export const SET_MESSAGES_FOR_STAFF_PANEL = 'app/StaffMain/SET_MESSAGES_FOR_STAFF_PANEL';
export const SET_HISTORY_FOR_STAFF_PANEL = 'app/StaffMain/SET_HISTORY_FOR_STAFF_PANEL';
export const SHOW_HISTORY_FOR_STAFF_PANEL = 'app/StaffMain/SHOW_HISTORY_FOR_STAFF_PANEL';

export const LOAD_MOST_RECENT_FOR_SUPERVISOR_PANEL = 'app/StaffMain/LOAD_MOST_RECENT_FOR_SUPERVISOR_PANEL';

export const SET_VISITOR_TYPING = 'app/StaffMain/SET_VISITOR_TYPING';

export const LOAD_UNHANDLED = 'app/StaffMain/LOAD_UNHANDLED';
export const ADD_UNHANDLED_CHAT = 'app/StaffMain/ADD_HANDLED_CHAT';
export const REMOVE_UNHANDLED_CHAT = 'app/StaffMain/REMOVE_UNHANDLED_CHATS';

export const LOAD_FLAGGED_CHATS = 'app/StaffMain/LOAD_FLAGGED_CHATS';

export const LOAD_STAFFS_HANDLING_VISITOR = 'app/StaffMain/LOAD_STAFFS_HANDLING_VISITOR'
export const SET_STAFFS_HANDLING_VISITOR = 'app/StaffMain/SET_STAFFS_HANDLING_VISITOR'

export const SET_ACTIVE_CHAT_HANDLED = 'app/StaffMain/SET_CHAT_HANDLED';

export const SET_ALL_UNHANDLED_CHATS = 'app/StaffMain/SET_ALL_UNHANDLED_CHATS';
export const REMOVE_FROM_ALL_UNHANDLED_CHATS = 'app/StaffMain/REMOVE_FROM_ALL_UNHANDLED_CHATS';
export const ADD_TO_ALL_UNHANDLED_CHATS = 'app/StaffMain/ADD_TO_ALL_UNHANDLED_CHATS';
export const LOAD_ALL_UNHANDLED_CHATS = 'app/StaffMain/LOAD_ALL_UNHANDLED_CHATS';

export const SET_MY_HANDLED_CHATS = 'app/StaffMain/SET_MY_HANDLED_CHATS';
export const LOAD_MY_HANDLED_CHATS = 'app/StaffMain/LOAD_MY_HANDLED_CHATS'
export const ADD_TO_MY_HANDLED_CHATS = 'app/StaffMain/ADD_TO_MY_HANDLED_CHATS';
export const REMOVE_FROM_MY_HANDLED_CHATS = 'app/StaffMain/REMOVE_FROM_MY_HANDLED_CHATS';

export const SET_MY_UNHANDLED_CHATS = 'app/StaffMain/SET_MY_UNHANDLED_CHATS';
export const ADD_TO_MY_UNHANDLED_CHATS = 'app/StaffMain/ADD_TO_MY_UNHANDLED_CHATS';
export const REMOVE_FROM_MY_UNHANDLED_CHATS = 'app/StaffMain/REMOVE_FROM_MY_UNHANDLED_CHATS';

export const SET_CHAT_UNREAD = 'app/StaffMain/SET_CHAT_UNREAD';